//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BizWTF.Core.BizTalk.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BizTalkDTADbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BizTalkDTADbEntities object using the connection string found in the 'BizTalkDTADbEntities' section of the application configuration file.
        /// </summary>
        public BizTalkDTADbEntities() : base("name=BizTalkDTADbEntities", "BizTalkDTADbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BizTalkDTADbEntities object.
        /// </summary>
        public BizTalkDTADbEntities(string connectionString) : base(connectionString, "BizTalkDTADbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BizTalkDTADbEntities object.
        /// </summary>
        public BizTalkDTADbEntities(EntityConnection connection) : base(connection, "BizTalkDTADbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_DebugTrace> dta_DebugTrace
        {
            get
            {
                if ((_dta_DebugTrace == null))
                {
                    _dta_DebugTrace = base.CreateObjectSet<dta_DebugTrace>("dta_DebugTrace");
                }
                return _dta_DebugTrace;
            }
        }
        private ObjectSet<dta_DebugTrace> _dta_DebugTrace;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_MessageInOutEvents> dta_MessageInOutEvents
        {
            get
            {
                if ((_dta_MessageInOutEvents == null))
                {
                    _dta_MessageInOutEvents = base.CreateObjectSet<dta_MessageInOutEvents>("dta_MessageInOutEvents");
                }
                return _dta_MessageInOutEvents;
            }
        }
        private ObjectSet<dta_MessageInOutEvents> _dta_MessageInOutEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_ServiceInstanceExceptions> dta_ServiceInstanceExceptions
        {
            get
            {
                if ((_dta_ServiceInstanceExceptions == null))
                {
                    _dta_ServiceInstanceExceptions = base.CreateObjectSet<dta_ServiceInstanceExceptions>("dta_ServiceInstanceExceptions");
                }
                return _dta_ServiceInstanceExceptions;
            }
        }
        private ObjectSet<dta_ServiceInstanceExceptions> _dta_ServiceInstanceExceptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_ServiceInstances> dta_ServiceInstances
        {
            get
            {
                if ((_dta_ServiceInstances == null))
                {
                    _dta_ServiceInstances = base.CreateObjectSet<dta_ServiceInstances>("dta_ServiceInstances");
                }
                return _dta_ServiceInstances;
            }
        }
        private ObjectSet<dta_ServiceInstances> _dta_ServiceInstances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_Services> dta_Services
        {
            get
            {
                if ((_dta_Services == null))
                {
                    _dta_Services = base.CreateObjectSet<dta_Services>("dta_Services");
                }
                return _dta_Services;
            }
        }
        private ObjectSet<dta_Services> _dta_Services;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_PortName> dta_PortName
        {
            get
            {
                if ((_dta_PortName == null))
                {
                    _dta_PortName = base.CreateObjectSet<dta_PortName>("dta_PortName");
                }
                return _dta_PortName;
            }
        }
        private ObjectSet<dta_PortName> _dta_PortName;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_SchemaName> dta_SchemaName
        {
            get
            {
                if ((_dta_SchemaName == null))
                {
                    _dta_SchemaName = base.CreateObjectSet<dta_SchemaName>("dta_SchemaName");
                }
                return _dta_SchemaName;
            }
        }
        private ObjectSet<dta_SchemaName> _dta_SchemaName;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dta_ServiceState> dta_ServiceState
        {
            get
            {
                if ((_dta_ServiceState == null))
                {
                    _dta_ServiceState = base.CreateObjectSet<dta_ServiceState>("dta_ServiceState");
                }
                return _dta_ServiceState;
            }
        }
        private ObjectSet<dta_ServiceState> _dta_ServiceState;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_DebugTrace EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_DebugTrace(dta_DebugTrace dta_DebugTrace)
        {
            base.AddObject("dta_DebugTrace", dta_DebugTrace);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_MessageInOutEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_MessageInOutEvents(dta_MessageInOutEvents dta_MessageInOutEvents)
        {
            base.AddObject("dta_MessageInOutEvents", dta_MessageInOutEvents);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_ServiceInstanceExceptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_ServiceInstanceExceptions(dta_ServiceInstanceExceptions dta_ServiceInstanceExceptions)
        {
            base.AddObject("dta_ServiceInstanceExceptions", dta_ServiceInstanceExceptions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_ServiceInstances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_ServiceInstances(dta_ServiceInstances dta_ServiceInstances)
        {
            base.AddObject("dta_ServiceInstances", dta_ServiceInstances);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_Services EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_Services(dta_Services dta_Services)
        {
            base.AddObject("dta_Services", dta_Services);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_PortName EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_PortName(dta_PortName dta_PortName)
        {
            base.AddObject("dta_PortName", dta_PortName);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_SchemaName EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_SchemaName(dta_SchemaName dta_SchemaName)
        {
            base.AddObject("dta_SchemaName", dta_SchemaName);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dta_ServiceState EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodta_ServiceState(dta_ServiceState dta_ServiceState)
        {
            base.AddObject("dta_ServiceState", dta_ServiceState);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_DebugTrace")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_DebugTrace : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_DebugTrace object.
        /// </summary>
        /// <param name="nDebugTraceId">Initial value of the nDebugTraceId property.</param>
        /// <param name="uidServiceInstanceId">Initial value of the uidServiceInstanceId property.</param>
        /// <param name="vtInstructionId">Initial value of the vtInstructionId property.</param>
        /// <param name="nServiceSequence">Initial value of the nServiceSequence property.</param>
        /// <param name="nBeginInternalSequence">Initial value of the nBeginInternalSequence property.</param>
        public static dta_DebugTrace Createdta_DebugTrace(global::System.Int64 nDebugTraceId, global::System.Guid uidServiceInstanceId, global::System.Guid vtInstructionId, global::System.Int32 nServiceSequence, global::System.Int32 nBeginInternalSequence)
        {
            dta_DebugTrace dta_DebugTrace = new dta_DebugTrace();
            dta_DebugTrace.nDebugTraceId = nDebugTraceId;
            dta_DebugTrace.uidServiceInstanceId = uidServiceInstanceId;
            dta_DebugTrace.vtInstructionId = vtInstructionId;
            dta_DebugTrace.nServiceSequence = nServiceSequence;
            dta_DebugTrace.nBeginInternalSequence = nBeginInternalSequence;
            return dta_DebugTrace;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nDebugTraceId
        {
            get
            {
                return _nDebugTraceId;
            }
            set
            {
                if (_nDebugTraceId != value)
                {
                    OnnDebugTraceIdChanging(value);
                    ReportPropertyChanging("nDebugTraceId");
                    _nDebugTraceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nDebugTraceId");
                    OnnDebugTraceIdChanged();
                }
            }
        }
        private global::System.Int64 _nDebugTraceId;
        partial void OnnDebugTraceIdChanging(global::System.Int64 value);
        partial void OnnDebugTraceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceInstanceId
        {
            get
            {
                return _uidServiceInstanceId;
            }
            set
            {
                if (_uidServiceInstanceId != value)
                {
                    OnuidServiceInstanceIdChanging(value);
                    ReportPropertyChanging("uidServiceInstanceId");
                    _uidServiceInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceInstanceId");
                    OnuidServiceInstanceIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceInstanceId;
        partial void OnuidServiceInstanceIdChanging(global::System.Guid value);
        partial void OnuidServiceInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid vtInstructionId
        {
            get
            {
                return _vtInstructionId;
            }
            set
            {
                if (_vtInstructionId != value)
                {
                    OnvtInstructionIdChanging(value);
                    ReportPropertyChanging("vtInstructionId");
                    _vtInstructionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("vtInstructionId");
                    OnvtInstructionIdChanged();
                }
            }
        }
        private global::System.Guid _vtInstructionId;
        partial void OnvtInstructionIdChanging(global::System.Guid value);
        partial void OnvtInstructionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nServiceSequence
        {
            get
            {
                return _nServiceSequence;
            }
            set
            {
                if (_nServiceSequence != value)
                {
                    OnnServiceSequenceChanging(value);
                    ReportPropertyChanging("nServiceSequence");
                    _nServiceSequence = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nServiceSequence");
                    OnnServiceSequenceChanged();
                }
            }
        }
        private global::System.Int32 _nServiceSequence;
        partial void OnnServiceSequenceChanging(global::System.Int32 value);
        partial void OnnServiceSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nBeginInternalSequence
        {
            get
            {
                return _nBeginInternalSequence;
            }
            set
            {
                if (_nBeginInternalSequence != value)
                {
                    OnnBeginInternalSequenceChanging(value);
                    ReportPropertyChanging("nBeginInternalSequence");
                    _nBeginInternalSequence = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nBeginInternalSequence");
                    OnnBeginInternalSequenceChanged();
                }
            }
        }
        private global::System.Int32 _nBeginInternalSequence;
        partial void OnnBeginInternalSequenceChanging(global::System.Int32 value);
        partial void OnnBeginInternalSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nEndInternalSequence
        {
            get
            {
                return _nEndInternalSequence;
            }
            set
            {
                OnnEndInternalSequenceChanging(value);
                ReportPropertyChanging("nEndInternalSequence");
                _nEndInternalSequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nEndInternalSequence");
                OnnEndInternalSequenceChanged();
            }
        }
        private Nullable<global::System.Int32> _nEndInternalSequence;
        partial void OnnEndInternalSequenceChanging(Nullable<global::System.Int32> value);
        partial void OnnEndInternalSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtBeginTimeStamp
        {
            get
            {
                return _dtBeginTimeStamp;
            }
            set
            {
                OndtBeginTimeStampChanging(value);
                ReportPropertyChanging("dtBeginTimeStamp");
                _dtBeginTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtBeginTimeStamp");
                OndtBeginTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtBeginTimeStamp;
        partial void OndtBeginTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OndtBeginTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtEndTimeStamp
        {
            get
            {
                return _dtEndTimeStamp;
            }
            set
            {
                OndtEndTimeStampChanging(value);
                ReportPropertyChanging("dtEndTimeStamp");
                _dtEndTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtEndTimeStamp");
                OndtEndTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtEndTimeStamp;
        partial void OndtEndTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OndtEndTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtInsertionTimeStamp
        {
            get
            {
                return _dtInsertionTimeStamp;
            }
            set
            {
                OndtInsertionTimeStampChanging(value);
                ReportPropertyChanging("dtInsertionTimeStamp");
                _dtInsertionTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtInsertionTimeStamp");
                OndtInsertionTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtInsertionTimeStamp;
        partial void OndtInsertionTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OndtInsertionTimeStampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_MessageInOutEvents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_MessageInOutEvents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_MessageInOutEvents object.
        /// </summary>
        /// <param name="nEventId">Initial value of the nEventId property.</param>
        /// <param name="uidActivityId">Initial value of the uidActivityId property.</param>
        /// <param name="uidServiceInstanceId">Initial value of the uidServiceInstanceId property.</param>
        /// <param name="uidMessageInstanceId">Initial value of the uidMessageInstanceId property.</param>
        /// <param name="nAdapterId">Initial value of the nAdapterId property.</param>
        /// <param name="nDecryptionSubjectId">Initial value of the nDecryptionSubjectId property.</param>
        /// <param name="nSigningSubjectId">Initial value of the nSigningSubjectId property.</param>
        /// <param name="nPartyId">Initial value of the nPartyId property.</param>
        /// <param name="nPortId">Initial value of the nPortId property.</param>
        /// <param name="dtTimestamp">Initial value of the dtTimestamp property.</param>
        /// <param name="nStatus">Initial value of the nStatus property.</param>
        /// <param name="nSchemaId">Initial value of the nSchemaId property.</param>
        public static dta_MessageInOutEvents Createdta_MessageInOutEvents(global::System.Int64 nEventId, global::System.Guid uidActivityId, global::System.Guid uidServiceInstanceId, global::System.Guid uidMessageInstanceId, global::System.Int64 nAdapterId, global::System.Int32 nDecryptionSubjectId, global::System.Int32 nSigningSubjectId, global::System.Int64 nPartyId, global::System.Int64 nPortId, global::System.DateTime dtTimestamp, global::System.Int32 nStatus, global::System.Int32 nSchemaId)
        {
            dta_MessageInOutEvents dta_MessageInOutEvents = new dta_MessageInOutEvents();
            dta_MessageInOutEvents.nEventId = nEventId;
            dta_MessageInOutEvents.uidActivityId = uidActivityId;
            dta_MessageInOutEvents.uidServiceInstanceId = uidServiceInstanceId;
            dta_MessageInOutEvents.uidMessageInstanceId = uidMessageInstanceId;
            dta_MessageInOutEvents.nAdapterId = nAdapterId;
            dta_MessageInOutEvents.nDecryptionSubjectId = nDecryptionSubjectId;
            dta_MessageInOutEvents.nSigningSubjectId = nSigningSubjectId;
            dta_MessageInOutEvents.nPartyId = nPartyId;
            dta_MessageInOutEvents.nPortId = nPortId;
            dta_MessageInOutEvents.dtTimestamp = dtTimestamp;
            dta_MessageInOutEvents.nStatus = nStatus;
            dta_MessageInOutEvents.nSchemaId = nSchemaId;
            return dta_MessageInOutEvents;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nEventId
        {
            get
            {
                return _nEventId;
            }
            set
            {
                if (_nEventId != value)
                {
                    OnnEventIdChanging(value);
                    ReportPropertyChanging("nEventId");
                    _nEventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nEventId");
                    OnnEventIdChanged();
                }
            }
        }
        private global::System.Int64 _nEventId;
        partial void OnnEventIdChanging(global::System.Int64 value);
        partial void OnnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidActivityId
        {
            get
            {
                return _uidActivityId;
            }
            set
            {
                if (_uidActivityId != value)
                {
                    OnuidActivityIdChanging(value);
                    ReportPropertyChanging("uidActivityId");
                    _uidActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidActivityId");
                    OnuidActivityIdChanged();
                }
            }
        }
        private global::System.Guid _uidActivityId;
        partial void OnuidActivityIdChanging(global::System.Guid value);
        partial void OnuidActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceInstanceId
        {
            get
            {
                return _uidServiceInstanceId;
            }
            set
            {
                if (_uidServiceInstanceId != value)
                {
                    OnuidServiceInstanceIdChanging(value);
                    ReportPropertyChanging("uidServiceInstanceId");
                    _uidServiceInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceInstanceId");
                    OnuidServiceInstanceIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceInstanceId;
        partial void OnuidServiceInstanceIdChanging(global::System.Guid value);
        partial void OnuidServiceInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidMessageInstanceId
        {
            get
            {
                return _uidMessageInstanceId;
            }
            set
            {
                if (_uidMessageInstanceId != value)
                {
                    OnuidMessageInstanceIdChanging(value);
                    ReportPropertyChanging("uidMessageInstanceId");
                    _uidMessageInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidMessageInstanceId");
                    OnuidMessageInstanceIdChanged();
                }
            }
        }
        private global::System.Guid _uidMessageInstanceId;
        partial void OnuidMessageInstanceIdChanging(global::System.Guid value);
        partial void OnuidMessageInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nAdapterId
        {
            get
            {
                return _nAdapterId;
            }
            set
            {
                if (_nAdapterId != value)
                {
                    OnnAdapterIdChanging(value);
                    ReportPropertyChanging("nAdapterId");
                    _nAdapterId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nAdapterId");
                    OnnAdapterIdChanged();
                }
            }
        }
        private global::System.Int64 _nAdapterId;
        partial void OnnAdapterIdChanging(global::System.Int64 value);
        partial void OnnAdapterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nDecryptionSubjectId
        {
            get
            {
                return _nDecryptionSubjectId;
            }
            set
            {
                if (_nDecryptionSubjectId != value)
                {
                    OnnDecryptionSubjectIdChanging(value);
                    ReportPropertyChanging("nDecryptionSubjectId");
                    _nDecryptionSubjectId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nDecryptionSubjectId");
                    OnnDecryptionSubjectIdChanged();
                }
            }
        }
        private global::System.Int32 _nDecryptionSubjectId;
        partial void OnnDecryptionSubjectIdChanging(global::System.Int32 value);
        partial void OnnDecryptionSubjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nSigningSubjectId
        {
            get
            {
                return _nSigningSubjectId;
            }
            set
            {
                if (_nSigningSubjectId != value)
                {
                    OnnSigningSubjectIdChanging(value);
                    ReportPropertyChanging("nSigningSubjectId");
                    _nSigningSubjectId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nSigningSubjectId");
                    OnnSigningSubjectIdChanged();
                }
            }
        }
        private global::System.Int32 _nSigningSubjectId;
        partial void OnnSigningSubjectIdChanging(global::System.Int32 value);
        partial void OnnSigningSubjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nPartyId
        {
            get
            {
                return _nPartyId;
            }
            set
            {
                if (_nPartyId != value)
                {
                    OnnPartyIdChanging(value);
                    ReportPropertyChanging("nPartyId");
                    _nPartyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nPartyId");
                    OnnPartyIdChanged();
                }
            }
        }
        private global::System.Int64 _nPartyId;
        partial void OnnPartyIdChanging(global::System.Int64 value);
        partial void OnnPartyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nPortId
        {
            get
            {
                return _nPortId;
            }
            set
            {
                if (_nPortId != value)
                {
                    OnnPortIdChanging(value);
                    ReportPropertyChanging("nPortId");
                    _nPortId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nPortId");
                    OnnPortIdChanged();
                }
            }
        }
        private global::System.Int64 _nPortId;
        partial void OnnPortIdChanging(global::System.Int64 value);
        partial void OnnPortIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtTimestamp
        {
            get
            {
                return _dtTimestamp;
            }
            set
            {
                if (_dtTimestamp != value)
                {
                    OndtTimestampChanging(value);
                    ReportPropertyChanging("dtTimestamp");
                    _dtTimestamp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dtTimestamp");
                    OndtTimestampChanged();
                }
            }
        }
        private global::System.DateTime _dtTimestamp;
        partial void OndtTimestampChanging(global::System.DateTime value);
        partial void OndtTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nStatus
        {
            get
            {
                return _nStatus;
            }
            set
            {
                if (_nStatus != value)
                {
                    OnnStatusChanging(value);
                    ReportPropertyChanging("nStatus");
                    _nStatus = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nStatus");
                    OnnStatusChanged();
                }
            }
        }
        private global::System.Int32 _nStatus;
        partial void OnnStatusChanging(global::System.Int32 value);
        partial void OnnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nSchemaId
        {
            get
            {
                return _nSchemaId;
            }
            set
            {
                if (_nSchemaId != value)
                {
                    OnnSchemaIdChanging(value);
                    ReportPropertyChanging("nSchemaId");
                    _nSchemaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nSchemaId");
                    OnnSchemaIdChanged();
                }
            }
        }
        private global::System.Int32 _nSchemaId;
        partial void OnnSchemaIdChanging(global::System.Int32 value);
        partial void OnnSchemaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nPartCount
        {
            get
            {
                return _nPartCount;
            }
            set
            {
                OnnPartCountChanging(value);
                ReportPropertyChanging("nPartCount");
                _nPartCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nPartCount");
                OnnPartCountChanged();
            }
        }
        private Nullable<global::System.Int32> _nPartCount;
        partial void OnnPartCountChanging(Nullable<global::System.Int32> value);
        partial void OnnPartCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> nMessageSize
        {
            get
            {
                return _nMessageSize;
            }
            set
            {
                OnnMessageSizeChanging(value);
                ReportPropertyChanging("nMessageSize");
                _nMessageSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nMessageSize");
                OnnMessageSizeChanged();
            }
        }
        private Nullable<global::System.Int64> _nMessageSize;
        partial void OnnMessageSizeChanging(Nullable<global::System.Int64> value);
        partial void OnnMessageSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strUrl
        {
            get
            {
                return _strUrl;
            }
            set
            {
                OnstrUrlChanging(value);
                ReportPropertyChanging("strUrl");
                _strUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strUrl");
                OnstrUrlChanged();
            }
        }
        private global::System.String _strUrl;
        partial void OnstrUrlChanging(global::System.String value);
        partial void OnstrUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtInsertionTimeStamp
        {
            get
            {
                return _dtInsertionTimeStamp;
            }
            set
            {
                OndtInsertionTimeStampChanging(value);
                ReportPropertyChanging("dtInsertionTimeStamp");
                _dtInsertionTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtInsertionTimeStamp");
                OndtInsertionTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtInsertionTimeStamp;
        partial void OndtInsertionTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OndtInsertionTimeStampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_PortName")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_PortName : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_PortName object.
        /// </summary>
        /// <param name="nPortId">Initial value of the nPortId property.</param>
        /// <param name="strPortName">Initial value of the strPortName property.</param>
        public static dta_PortName Createdta_PortName(global::System.Int32 nPortId, global::System.String strPortName)
        {
            dta_PortName dta_PortName = new dta_PortName();
            dta_PortName.nPortId = nPortId;
            dta_PortName.strPortName = strPortName;
            return dta_PortName;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nPortId
        {
            get
            {
                return _nPortId;
            }
            set
            {
                if (_nPortId != value)
                {
                    OnnPortIdChanging(value);
                    ReportPropertyChanging("nPortId");
                    _nPortId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nPortId");
                    OnnPortIdChanged();
                }
            }
        }
        private global::System.Int32 _nPortId;
        partial void OnnPortIdChanging(global::System.Int32 value);
        partial void OnnPortIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strPortName
        {
            get
            {
                return _strPortName;
            }
            set
            {
                OnstrPortNameChanging(value);
                ReportPropertyChanging("strPortName");
                _strPortName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strPortName");
                OnstrPortNameChanged();
            }
        }
        private global::System.String _strPortName;
        partial void OnstrPortNameChanging(global::System.String value);
        partial void OnstrPortNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_SchemaName")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_SchemaName : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_SchemaName object.
        /// </summary>
        /// <param name="nSchemaId">Initial value of the nSchemaId property.</param>
        /// <param name="strSchemaName">Initial value of the strSchemaName property.</param>
        public static dta_SchemaName Createdta_SchemaName(global::System.Int32 nSchemaId, global::System.String strSchemaName)
        {
            dta_SchemaName dta_SchemaName = new dta_SchemaName();
            dta_SchemaName.nSchemaId = nSchemaId;
            dta_SchemaName.strSchemaName = strSchemaName;
            return dta_SchemaName;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nSchemaId
        {
            get
            {
                return _nSchemaId;
            }
            set
            {
                if (_nSchemaId != value)
                {
                    OnnSchemaIdChanging(value);
                    ReportPropertyChanging("nSchemaId");
                    _nSchemaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nSchemaId");
                    OnnSchemaIdChanged();
                }
            }
        }
        private global::System.Int32 _nSchemaId;
        partial void OnnSchemaIdChanging(global::System.Int32 value);
        partial void OnnSchemaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strSchemaName
        {
            get
            {
                return _strSchemaName;
            }
            set
            {
                OnstrSchemaNameChanging(value);
                ReportPropertyChanging("strSchemaName");
                _strSchemaName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strSchemaName");
                OnstrSchemaNameChanged();
            }
        }
        private global::System.String _strSchemaName;
        partial void OnstrSchemaNameChanging(global::System.String value);
        partial void OnstrSchemaNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_ServiceInstanceExceptions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_ServiceInstanceExceptions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_ServiceInstanceExceptions object.
        /// </summary>
        /// <param name="uidActivityId">Initial value of the uidActivityId property.</param>
        /// <param name="uidServiceInstanceId">Initial value of the uidServiceInstanceId property.</param>
        /// <param name="bTopLevelException">Initial value of the bTopLevelException property.</param>
        public static dta_ServiceInstanceExceptions Createdta_ServiceInstanceExceptions(global::System.Guid uidActivityId, global::System.Guid uidServiceInstanceId, global::System.Int32 bTopLevelException)
        {
            dta_ServiceInstanceExceptions dta_ServiceInstanceExceptions = new dta_ServiceInstanceExceptions();
            dta_ServiceInstanceExceptions.uidActivityId = uidActivityId;
            dta_ServiceInstanceExceptions.uidServiceInstanceId = uidServiceInstanceId;
            dta_ServiceInstanceExceptions.bTopLevelException = bTopLevelException;
            return dta_ServiceInstanceExceptions;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidActivityId
        {
            get
            {
                return _uidActivityId;
            }
            set
            {
                if (_uidActivityId != value)
                {
                    OnuidActivityIdChanging(value);
                    ReportPropertyChanging("uidActivityId");
                    _uidActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidActivityId");
                    OnuidActivityIdChanged();
                }
            }
        }
        private global::System.Guid _uidActivityId;
        partial void OnuidActivityIdChanging(global::System.Guid value);
        partial void OnuidActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceInstanceId
        {
            get
            {
                return _uidServiceInstanceId;
            }
            set
            {
                if (_uidServiceInstanceId != value)
                {
                    OnuidServiceInstanceIdChanging(value);
                    ReportPropertyChanging("uidServiceInstanceId");
                    _uidServiceInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceInstanceId");
                    OnuidServiceInstanceIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceInstanceId;
        partial void OnuidServiceInstanceIdChanging(global::System.Guid value);
        partial void OnuidServiceInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bTopLevelException
        {
            get
            {
                return _bTopLevelException;
            }
            set
            {
                if (_bTopLevelException != value)
                {
                    OnbTopLevelExceptionChanging(value);
                    ReportPropertyChanging("bTopLevelException");
                    _bTopLevelException = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bTopLevelException");
                    OnbTopLevelExceptionChanged();
                }
            }
        }
        private global::System.Int32 _bTopLevelException;
        partial void OnbTopLevelExceptionChanging(global::System.Int32 value);
        partial void OnbTopLevelExceptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txtErrorInfo
        {
            get
            {
                return _txtErrorInfo;
            }
            set
            {
                OntxtErrorInfoChanging(value);
                ReportPropertyChanging("txtErrorInfo");
                _txtErrorInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txtErrorInfo");
                OntxtErrorInfoChanged();
            }
        }
        private global::System.String _txtErrorInfo;
        partial void OntxtErrorInfoChanging(global::System.String value);
        partial void OntxtErrorInfoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_ServiceInstances")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_ServiceInstances : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_ServiceInstances object.
        /// </summary>
        /// <param name="nServiceInstanceId">Initial value of the nServiceInstanceId property.</param>
        /// <param name="uidActivityId">Initial value of the uidActivityId property.</param>
        /// <param name="uidServiceInstanceId">Initial value of the uidServiceInstanceId property.</param>
        /// <param name="uidServiceId">Initial value of the uidServiceId property.</param>
        /// <param name="uidAgentSrvId">Initial value of the uidAgentSrvId property.</param>
        /// <param name="uidServiceClassId">Initial value of the uidServiceClassId property.</param>
        /// <param name="dtStartTime">Initial value of the dtStartTime property.</param>
        /// <param name="nHostId">Initial value of the nHostId property.</param>
        /// <param name="nMessageBoxId">Initial value of the nMessageBoxId property.</param>
        /// <param name="nServiceStateId">Initial value of the nServiceStateId property.</param>
        /// <param name="nGroupId">Initial value of the nGroupId property.</param>
        /// <param name="bExceptionsOccurred">Initial value of the bExceptionsOccurred property.</param>
        public static dta_ServiceInstances Createdta_ServiceInstances(global::System.Int64 nServiceInstanceId, global::System.Guid uidActivityId, global::System.Guid uidServiceInstanceId, global::System.Guid uidServiceId, global::System.Guid uidAgentSrvId, global::System.Guid uidServiceClassId, global::System.DateTime dtStartTime, global::System.Int32 nHostId, global::System.Int32 nMessageBoxId, global::System.Int32 nServiceStateId, global::System.Int32 nGroupId, global::System.Int32 bExceptionsOccurred)
        {
            dta_ServiceInstances dta_ServiceInstances = new dta_ServiceInstances();
            dta_ServiceInstances.nServiceInstanceId = nServiceInstanceId;
            dta_ServiceInstances.uidActivityId = uidActivityId;
            dta_ServiceInstances.uidServiceInstanceId = uidServiceInstanceId;
            dta_ServiceInstances.uidServiceId = uidServiceId;
            dta_ServiceInstances.uidAgentSrvId = uidAgentSrvId;
            dta_ServiceInstances.uidServiceClassId = uidServiceClassId;
            dta_ServiceInstances.dtStartTime = dtStartTime;
            dta_ServiceInstances.nHostId = nHostId;
            dta_ServiceInstances.nMessageBoxId = nMessageBoxId;
            dta_ServiceInstances.nServiceStateId = nServiceStateId;
            dta_ServiceInstances.nGroupId = nGroupId;
            dta_ServiceInstances.bExceptionsOccurred = bExceptionsOccurred;
            return dta_ServiceInstances;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nServiceInstanceId
        {
            get
            {
                return _nServiceInstanceId;
            }
            set
            {
                if (_nServiceInstanceId != value)
                {
                    OnnServiceInstanceIdChanging(value);
                    ReportPropertyChanging("nServiceInstanceId");
                    _nServiceInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nServiceInstanceId");
                    OnnServiceInstanceIdChanged();
                }
            }
        }
        private global::System.Int64 _nServiceInstanceId;
        partial void OnnServiceInstanceIdChanging(global::System.Int64 value);
        partial void OnnServiceInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidActivityId
        {
            get
            {
                return _uidActivityId;
            }
            set
            {
                if (_uidActivityId != value)
                {
                    OnuidActivityIdChanging(value);
                    ReportPropertyChanging("uidActivityId");
                    _uidActivityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidActivityId");
                    OnuidActivityIdChanged();
                }
            }
        }
        private global::System.Guid _uidActivityId;
        partial void OnuidActivityIdChanging(global::System.Guid value);
        partial void OnuidActivityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceInstanceId
        {
            get
            {
                return _uidServiceInstanceId;
            }
            set
            {
                if (_uidServiceInstanceId != value)
                {
                    OnuidServiceInstanceIdChanging(value);
                    ReportPropertyChanging("uidServiceInstanceId");
                    _uidServiceInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceInstanceId");
                    OnuidServiceInstanceIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceInstanceId;
        partial void OnuidServiceInstanceIdChanging(global::System.Guid value);
        partial void OnuidServiceInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceId
        {
            get
            {
                return _uidServiceId;
            }
            set
            {
                if (_uidServiceId != value)
                {
                    OnuidServiceIdChanging(value);
                    ReportPropertyChanging("uidServiceId");
                    _uidServiceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceId");
                    OnuidServiceIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceId;
        partial void OnuidServiceIdChanging(global::System.Guid value);
        partial void OnuidServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidAgentSrvId
        {
            get
            {
                return _uidAgentSrvId;
            }
            set
            {
                if (_uidAgentSrvId != value)
                {
                    OnuidAgentSrvIdChanging(value);
                    ReportPropertyChanging("uidAgentSrvId");
                    _uidAgentSrvId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidAgentSrvId");
                    OnuidAgentSrvIdChanged();
                }
            }
        }
        private global::System.Guid _uidAgentSrvId;
        partial void OnuidAgentSrvIdChanging(global::System.Guid value);
        partial void OnuidAgentSrvIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceClassId
        {
            get
            {
                return _uidServiceClassId;
            }
            set
            {
                if (_uidServiceClassId != value)
                {
                    OnuidServiceClassIdChanging(value);
                    ReportPropertyChanging("uidServiceClassId");
                    _uidServiceClassId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceClassId");
                    OnuidServiceClassIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceClassId;
        partial void OnuidServiceClassIdChanging(global::System.Guid value);
        partial void OnuidServiceClassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtStartTime
        {
            get
            {
                return _dtStartTime;
            }
            set
            {
                if (_dtStartTime != value)
                {
                    OndtStartTimeChanging(value);
                    ReportPropertyChanging("dtStartTime");
                    _dtStartTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dtStartTime");
                    OndtStartTimeChanged();
                }
            }
        }
        private global::System.DateTime _dtStartTime;
        partial void OndtStartTimeChanging(global::System.DateTime value);
        partial void OndtStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtEndTime
        {
            get
            {
                return _dtEndTime;
            }
            set
            {
                OndtEndTimeChanging(value);
                ReportPropertyChanging("dtEndTime");
                _dtEndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtEndTime");
                OndtEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtEndTime;
        partial void OndtEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OndtEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> HRESULT
        {
            get
            {
                return _HRESULT;
            }
            set
            {
                OnHRESULTChanging(value);
                ReportPropertyChanging("HRESULT");
                _HRESULT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HRESULT");
                OnHRESULTChanged();
            }
        }
        private Nullable<global::System.Int64> _HRESULT;
        partial void OnHRESULTChanging(Nullable<global::System.Int64> value);
        partial void OnHRESULTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorInfo
        {
            get
            {
                return _ErrorInfo;
            }
            set
            {
                OnErrorInfoChanging(value);
                ReportPropertyChanging("ErrorInfo");
                _ErrorInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorInfo");
                OnErrorInfoChanged();
            }
        }
        private global::System.String _ErrorInfo;
        partial void OnErrorInfoChanging(global::System.String value);
        partial void OnErrorInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nHostId
        {
            get
            {
                return _nHostId;
            }
            set
            {
                if (_nHostId != value)
                {
                    OnnHostIdChanging(value);
                    ReportPropertyChanging("nHostId");
                    _nHostId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nHostId");
                    OnnHostIdChanged();
                }
            }
        }
        private global::System.Int32 _nHostId;
        partial void OnnHostIdChanging(global::System.Int32 value);
        partial void OnnHostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nMessageBoxId
        {
            get
            {
                return _nMessageBoxId;
            }
            set
            {
                if (_nMessageBoxId != value)
                {
                    OnnMessageBoxIdChanging(value);
                    ReportPropertyChanging("nMessageBoxId");
                    _nMessageBoxId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nMessageBoxId");
                    OnnMessageBoxIdChanged();
                }
            }
        }
        private global::System.Int32 _nMessageBoxId;
        partial void OnnMessageBoxIdChanging(global::System.Int32 value);
        partial void OnnMessageBoxIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nServiceStateId
        {
            get
            {
                return _nServiceStateId;
            }
            set
            {
                if (_nServiceStateId != value)
                {
                    OnnServiceStateIdChanging(value);
                    ReportPropertyChanging("nServiceStateId");
                    _nServiceStateId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nServiceStateId");
                    OnnServiceStateIdChanged();
                }
            }
        }
        private global::System.Int32 _nServiceStateId;
        partial void OnnServiceStateIdChanging(global::System.Int32 value);
        partial void OnnServiceStateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nGroupId
        {
            get
            {
                return _nGroupId;
            }
            set
            {
                if (_nGroupId != value)
                {
                    OnnGroupIdChanging(value);
                    ReportPropertyChanging("nGroupId");
                    _nGroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nGroupId");
                    OnnGroupIdChanged();
                }
            }
        }
        private global::System.Int32 _nGroupId;
        partial void OnnGroupIdChanging(global::System.Int32 value);
        partial void OnnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bExceptionsOccurred
        {
            get
            {
                return _bExceptionsOccurred;
            }
            set
            {
                if (_bExceptionsOccurred != value)
                {
                    OnbExceptionsOccurredChanging(value);
                    ReportPropertyChanging("bExceptionsOccurred");
                    _bExceptionsOccurred = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bExceptionsOccurred");
                    OnbExceptionsOccurredChanged();
                }
            }
        }
        private global::System.Int32 _bExceptionsOccurred;
        partial void OnbExceptionsOccurredChanging(global::System.Int32 value);
        partial void OnbExceptionsOccurredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtInsertionTimeStamp
        {
            get
            {
                return _dtInsertionTimeStamp;
            }
            set
            {
                OndtInsertionTimeStampChanging(value);
                ReportPropertyChanging("dtInsertionTimeStamp");
                _dtInsertionTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtInsertionTimeStamp");
                OndtInsertionTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtInsertionTimeStamp;
        partial void OndtInsertionTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OndtInsertionTimeStampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_Services")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_Services : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_Services object.
        /// </summary>
        /// <param name="nServiceId">Initial value of the nServiceId property.</param>
        /// <param name="uidServiceId">Initial value of the uidServiceId property.</param>
        /// <param name="uidNonVersionId">Initial value of the uidNonVersionId property.</param>
        /// <param name="strServiceType">Initial value of the strServiceType property.</param>
        /// <param name="strServiceName">Initial value of the strServiceName property.</param>
        /// <param name="dtDeploymentTime">Initial value of the dtDeploymentTime property.</param>
        public static dta_Services Createdta_Services(global::System.Int64 nServiceId, global::System.Guid uidServiceId, global::System.Guid uidNonVersionId, global::System.String strServiceType, global::System.String strServiceName, global::System.DateTime dtDeploymentTime)
        {
            dta_Services dta_Services = new dta_Services();
            dta_Services.nServiceId = nServiceId;
            dta_Services.uidServiceId = uidServiceId;
            dta_Services.uidNonVersionId = uidNonVersionId;
            dta_Services.strServiceType = strServiceType;
            dta_Services.strServiceName = strServiceName;
            dta_Services.dtDeploymentTime = dtDeploymentTime;
            return dta_Services;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 nServiceId
        {
            get
            {
                return _nServiceId;
            }
            set
            {
                OnnServiceIdChanging(value);
                ReportPropertyChanging("nServiceId");
                _nServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nServiceId");
                OnnServiceIdChanged();
            }
        }
        private global::System.Int64 _nServiceId;
        partial void OnnServiceIdChanging(global::System.Int64 value);
        partial void OnnServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidServiceId
        {
            get
            {
                return _uidServiceId;
            }
            set
            {
                if (_uidServiceId != value)
                {
                    OnuidServiceIdChanging(value);
                    ReportPropertyChanging("uidServiceId");
                    _uidServiceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uidServiceId");
                    OnuidServiceIdChanged();
                }
            }
        }
        private global::System.Guid _uidServiceId;
        partial void OnuidServiceIdChanging(global::System.Guid value);
        partial void OnuidServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uidNonVersionId
        {
            get
            {
                return _uidNonVersionId;
            }
            set
            {
                OnuidNonVersionIdChanging(value);
                ReportPropertyChanging("uidNonVersionId");
                _uidNonVersionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uidNonVersionId");
                OnuidNonVersionIdChanged();
            }
        }
        private global::System.Guid _uidNonVersionId;
        partial void OnuidNonVersionIdChanging(global::System.Guid value);
        partial void OnuidNonVersionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strServiceType
        {
            get
            {
                return _strServiceType;
            }
            set
            {
                OnstrServiceTypeChanging(value);
                ReportPropertyChanging("strServiceType");
                _strServiceType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strServiceType");
                OnstrServiceTypeChanged();
            }
        }
        private global::System.String _strServiceType;
        partial void OnstrServiceTypeChanging(global::System.String value);
        partial void OnstrServiceTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strServiceName
        {
            get
            {
                return _strServiceName;
            }
            set
            {
                OnstrServiceNameChanging(value);
                ReportPropertyChanging("strServiceName");
                _strServiceName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strServiceName");
                OnstrServiceNameChanged();
            }
        }
        private global::System.String _strServiceName;
        partial void OnstrServiceNameChanging(global::System.String value);
        partial void OnstrServiceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strAssemblyName
        {
            get
            {
                return _strAssemblyName;
            }
            set
            {
                OnstrAssemblyNameChanging(value);
                ReportPropertyChanging("strAssemblyName");
                _strAssemblyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strAssemblyName");
                OnstrAssemblyNameChanged();
            }
        }
        private global::System.String _strAssemblyName;
        partial void OnstrAssemblyNameChanging(global::System.String value);
        partial void OnstrAssemblyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strAssemblyVersion
        {
            get
            {
                return _strAssemblyVersion;
            }
            set
            {
                OnstrAssemblyVersionChanging(value);
                ReportPropertyChanging("strAssemblyVersion");
                _strAssemblyVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strAssemblyVersion");
                OnstrAssemblyVersionChanged();
            }
        }
        private global::System.String _strAssemblyVersion;
        partial void OnstrAssemblyVersionChanging(global::System.String value);
        partial void OnstrAssemblyVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtDeploymentTime
        {
            get
            {
                return _dtDeploymentTime;
            }
            set
            {
                OndtDeploymentTimeChanging(value);
                ReportPropertyChanging("dtDeploymentTime");
                _dtDeploymentTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtDeploymentTime");
                OndtDeploymentTimeChanged();
            }
        }
        private global::System.DateTime _dtDeploymentTime;
        partial void OndtDeploymentTimeChanging(global::System.DateTime value);
        partial void OndtDeploymentTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txtSymbol
        {
            get
            {
                return _txtSymbol;
            }
            set
            {
                OntxtSymbolChanging(value);
                ReportPropertyChanging("txtSymbol");
                _txtSymbol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txtSymbol");
                OntxtSymbolChanged();
            }
        }
        private global::System.String _txtSymbol;
        partial void OntxtSymbolChanging(global::System.String value);
        partial void OntxtSymbolChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BizTalkDTADbModel", Name="dta_ServiceState")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dta_ServiceState : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dta_ServiceState object.
        /// </summary>
        /// <param name="nServiceStateId">Initial value of the nServiceStateId property.</param>
        /// <param name="strState">Initial value of the strState property.</param>
        public static dta_ServiceState Createdta_ServiceState(global::System.Int32 nServiceStateId, global::System.String strState)
        {
            dta_ServiceState dta_ServiceState = new dta_ServiceState();
            dta_ServiceState.nServiceStateId = nServiceStateId;
            dta_ServiceState.strState = strState;
            return dta_ServiceState;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nServiceStateId
        {
            get
            {
                return _nServiceStateId;
            }
            set
            {
                if (_nServiceStateId != value)
                {
                    OnnServiceStateIdChanging(value);
                    ReportPropertyChanging("nServiceStateId");
                    _nServiceStateId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nServiceStateId");
                    OnnServiceStateIdChanged();
                }
            }
        }
        private global::System.Int32 _nServiceStateId;
        partial void OnnServiceStateIdChanging(global::System.Int32 value);
        partial void OnnServiceStateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strState
        {
            get
            {
                return _strState;
            }
            set
            {
                OnstrStateChanging(value);
                ReportPropertyChanging("strState");
                _strState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strState");
                OnstrStateChanged();
            }
        }
        private global::System.String _strState;
        partial void OnstrStateChanging(global::System.String value);
        partial void OnstrStateChanged();

        #endregion

    
    }

    #endregion

    
}
