//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace BizWTF.Core.Entities {
    using System.Xml.Serialization;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.Text;


    public struct Namespaces
    {
        public const string SUBMISSION = "http://BizWTF.Mocking.Schemas.Submission";
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = Namespaces.SUBMISSION)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "MultipartMessage", Namespace = Namespaces.SUBMISSION, IsNullable = false)]
    [DataContract(Name = "MultipartMessage", Namespace = Namespaces.SUBMISSION)]
    public partial class MultipartMessageDefinition
    {
        
        private string descriptionField;
        
        private ContextProperty[] propertyBagField;
        
        private Part[] partsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, IsNullable=true)]
        [DataMember(Order = 0)]
        public string Description
        {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ContextProperty", IsNullable=false)]
        [DataMember(Order = 1)]
        public ContextProperty[] PropertyBag
        {
            get {
                if (this.propertyBagField == null)
                    this.propertyBagField = new ContextProperty[0];
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Part", IsNullable=false)]
        [DataMember(Order = 2)]
        public Part[] Parts
        {
            get {
                if (this.partsField == null)
                    this.partsField = new Part[0];
                return this.partsField;
            }
            set {
                this.partsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = Namespaces.SUBMISSION)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = Namespaces.SUBMISSION, IsNullable = false)]
    [DataContract(Name = "ContextProperty", Namespace = Namespaces.SUBMISSION)]
    public partial class ContextProperty
    {
        
        private string nameField;
        
        private string namespaceField;
        
        private string valueField;
        
        private bool promotedField;
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 0), XmlElement]
        public string Name
        {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 1), XmlElement]
        public string Namespace
        {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 2), XmlElement]
        public string Value
        {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 3), XmlElement]
        public bool Promoted
        {
            get {
                return this.promotedField;
            }
            set {
                this.promotedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = Namespaces.SUBMISSION)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false, Namespace = Namespaces.SUBMISSION)]
    [DataContract(Name = "Part", Namespace = Namespaces.SUBMISSION)]
    public partial class Part
    {

        private System.Xml.XmlElement dataField;
        private string rawDataField;
        
        private string partNameField;
        
        private int partNumberField;
        
        private bool partNumberFieldSpecified;
        
        private string contentTypeField;
        
        private bool isBodyPartField;



        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 0), XmlElement]
        public string PartName
        {
            get
            {
                return this.partNameField;
            }
            set
            {
                this.partNameField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 1), XmlElement]
        public int PartNumber
        {
            get
            {
                return this.partNumberField;
            }
            set
            {
                this.partNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        //[DataMember, XmlAttribute]
        public bool PartNumberSpecified
        {
            get
            {
                return this.partNumberFieldSpecified;
            }
            set
            {
                this.partNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 2), XmlElement]
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember(Order = 3), XmlElement]
        public bool IsBodyPart
        {
            get
            {
                return this.isBodyPartField;
            }
            set
            {
                this.isBodyPartField = value;
            }
        }

        
        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [DataMember(Order = 4), XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlElement Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [DataMember(Order = 5), XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = Namespaces.SUBMISSION)]
        public string RawData
        {
            get
            {
                return this.rawDataField;
            }
            set
            {
                this.rawDataField = value;
            }
        }
    }
}
