//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace NWT.Testing.Library.Entities {
    using System.Xml.Serialization;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.Text;

    internal struct Namespaces
    {
        public const string SUBMISSION = "http://NWT.Mocking.Schemas.Submission";
    }
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = Namespaces.SUBMISSION)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace=Namespaces.SUBMISSION, IsNullable=false)]
    [DataContract(Name = "MultipartMessage", Namespace = Namespaces.SUBMISSION)]
    public partial class MultipartMessage {
        
        private string descriptionField;
        
        private ContextProperty[] propertyBagField;
        
        private Part[] partsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [DataMember]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ContextProperty", IsNullable=false)]
        [DataMember]
        public ContextProperty[] PropertyBag
        {
            get {
                return this.propertyBagField;
            }
            set {
                this.propertyBagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Part", IsNullable=false)]
        [DataMember]
        public Part[] Parts
        {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NWT.Mocking.Schemas.Submission")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://NWT.Mocking.Schemas.Submission", IsNullable=false)]
    [DataContract(Name = "ContextProperty", Namespace = Namespaces.SUBMISSION)]
    public partial class ContextProperty
    {
        
        private string nameField;
        
        private string namespaceField;
        
        private string valueField;
        
        private bool promotedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public string Name
        {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public string Namespace
        {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public string Value
        {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public bool Promoted
        {
            get {
                return this.promotedField;
            }
            set {
                this.promotedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NWT.Mocking.Schemas.Submission")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://NWT.Mocking.Schemas.Submission", IsNullable=false)]
    [DataContract(Name = "Part", Namespace = Namespaces.SUBMISSION)]
    public partial class Part
    {
        
        private System.Xml.XmlElement dataField;
        
        private string partNameField;
        
        private int partNumberField;
        
        private bool partNumberFieldSpecified;
        
        private string contentTypeField;
        
        private bool isBodyPartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [DataMember]
        public System.Xml.XmlElement Data
        {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public string PartName
        {
            get {
                return this.partNameField;
            }
            set {
                this.partNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public int PartNumber
        {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool PartNumberSpecified
        {
            get {
                return this.partNumberFieldSpecified;
            }
            set {
                this.partNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public string ContentType
        {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataMember]
        public bool IsBodyPart
        {
            get {
                return this.isBodyPartField;
            }
            set {
                this.isBodyPartField = value;
            }
        }
    }
}
