//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizWTF.Core.BizTalk2WayReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.microsoft.com/biztalk/2006/r2/wcf-adapter", ConfigurationName="BizTalk2WayReference.ITwoWayAsync")]
    public interface ITwoWayAsync {
        
        [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.microsoft.com/biztalk/2006/r2/wcf-adapter/ITwoWayAsync/BizTalkSubmitRe" +
            "sponse")]
        System.ServiceModel.Channels.Message BizTalkSubmit(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwoWayAsyncChannel : BizWTF.Core.BizTalk2WayReference.ITwoWayAsync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwoWayAsyncClient : System.ServiceModel.ClientBase<BizWTF.Core.BizTalk2WayReference.ITwoWayAsync>, BizWTF.Core.BizTalk2WayReference.ITwoWayAsync {
        
        public TwoWayAsyncClient() {
        }
        
        public TwoWayAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwoWayAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoWayAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoWayAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message BizTalkSubmit(System.ServiceModel.Channels.Message request) {
            return base.Channel.BizTalkSubmit(request);
        }
    }
}
