//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizWTF.Core.BizTalk1WayReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.microsoft.com/biztalk/2006/r2/wcf-adapter", ConfigurationName="BizTalk1WayReference.ITwoWayAsyncVoid")]
    public interface ITwoWayAsyncVoid {
        
        [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.microsoft.com/biztalk/2006/r2/wcf-adapter/ITwoWayAsyncVoid/BizTalkSubm" +
            "itResponse")]
        void BizTalkSubmit(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwoWayAsyncVoidChannel : BizWTF.Core.BizTalk1WayReference.ITwoWayAsyncVoid, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwoWayAsyncVoidClient : System.ServiceModel.ClientBase<BizWTF.Core.BizTalk1WayReference.ITwoWayAsyncVoid>, BizWTF.Core.BizTalk1WayReference.ITwoWayAsyncVoid {
        
        public TwoWayAsyncVoidClient() {
        }
        
        public TwoWayAsyncVoidClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwoWayAsyncVoidClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoWayAsyncVoidClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwoWayAsyncVoidClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BizTalkSubmit(System.ServiceModel.Channels.Message request) {
            base.Channel.BizTalkSubmit(request);
        }
    }
}
